services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=orcamento'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
    cpus: 0.5
    mem_limit: 2g
